CREATE DATABASE IF NOT EXISTS gourmet CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'gourmet' IDENTIFIED BY 'gourmet';
GRANT ALL ON *.* TO gourmet@'%' IDENTIFIED BY 'gourmet' WITH GRANT OPTION;

FLUSH PRIVILEGES;